import clsx from 'clsx';
import Heading from '@theme/Heading';
import styles from './styles.module.css';

const FeatureList = [
  {
    title: 'New Home for the RC51 ECU Wiki',
    Svg: require('@site/static/img/undraw_docusaurus_mountain.svg').default,
    description: (
      <>
        This site is the new home of the RC51 ECU Conversion Wiki.  
        The previous version, hosted on <strong>hondarc51.frappe.cloud</strong>, had reliability issues —
        especially on mobile — and became increasingly difficult to maintain.  
        This migration ensures a smoother, faster, and more stable experience for everyone.
      </>
    ),
  },
  {
    title: 'Why Move Away From Frappe Wiki?',
    Svg: require('@site/static/img/undraw_docusaurus_tree.svg').default,
    description: (
      <>
        The old platform struggled with mobile rendering, theme inconsistencies, and layout bugs.
        Updating content required workarounds, and the editor often broke formatting.  
        Docusaurus solves these problems with predictable behavior, clean Markdown support,
        and a modern documentation engine built for technical projects like this one.
      </>
    ),
  },
  {
    title: 'Why Docusaurus Is Better',
    Svg: require('@site/static/img/undraw_docusaurus_react.svg').default,
    description: (
      <>
        Docusaurus offers versioning, autogenerated sidebars, React extensibility, and a powerful
        Markdown/MDX pipeline.  
        It’s easier to maintain, easier to scale, and far more reliable for long‑term documentation.
        This platform lets the project grow without fighting the tooling.
      </>
    ),
  },
];

function Feature({Svg, title, description}) {
  return (
    <div className={clsx('col col--4')}>
      <div className="text--center">
        <Svg className={styles.featureSvg} role="img" />
      </div>
      <div className="text--center padding-horiz--md">
        <Heading as="h3">{title}</Heading>
        <p>{description}</p>
      </div>
    </div>
  );
}

export default function HomepageFeatures() {
  return (
    <section className={styles.features}>
      <div className="container">
        <div className="row">
          {FeatureList.map((props, idx) => (
            <Feature key={idx} {...props} />
          ))}
        </div>
      </div>
    </section>
  );
}
